aliases:
  - &android
    components:
      - tools
      - platform-tools
      - extra-google-m2repository
    licenses:
      - "android-sdk-preview-license-52d11cd2"
      - "android-sdk-license-.+"
      - "google-gdk-license-.+"

  - &android-cache
    directories:
      - ~/.cache/yarn
      - ~/.gradle/caches
      - ~/.gradle/wrapper
      - ~/.android/build-cache

  - &ios-cache
    directories:
      - ~/.rncache
      - ~/Library/Caches/Yarn
      - ~/Library/Caches/CocoaPods

jobs:
  include:
    - stage: ios-beta
      if: branch = master AND type = push
      os: osx
      osx_image: xcode11.3
      language: node_js
      cache: *ios-cache
      node_js:
        - lts/*
      before_install:
        - sudo gem install fastlane
        - npm install -g yarn
      install:
        - "./write-ios-keys.sh"
        - "./install-deps-ios.sh"
      script:
        - "./deploy-ios-beta.sh"

    - stage: android-beta
      if: branch = master AND type = push
      language: android
      jdk: oraclejdk8
      android: *android
      cache: *android-cache
      before_install:
        - rvm install 2.6.5
        - gem install fastlane
        - nvm install 10.17.0
        - npm install -g yarn
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
      install:
        - "./write-android-keys.sh"
        - "./install-deps-android.sh"
      script:
        - "./deploy-android-beta.sh"

env:
  global:
    - APP_NAME="Memex Go"
    - 'DEVELOPER_NAME="iPhone Distribution: WorldBrain UG (haftungsbeschränkt)"'
    - PROFILE_NAME="travis"
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
