jobs:
  include:
    - stage: ios-beta
      # if: branch = develop AND type = push
      os: osx
      osx_image: xcode11.3
      language: node_js
      node_js:
        - lts/*
      before_install:
        - "./write-keys.sh"
        - npm install -g yarn
      install:
        - "./install-deps.sh"
      script:
        - yarn ios:beta
env:
  global:
    - APP_NAME="Memex Mobile"
    - 'DEVELOPER_NAME="iPhone Distribution: WorldBrain UG (haftungsbeschränkt)"'
    - PROFILE_NAME="travis"
