aliases:
  - &android
    components:
      - tools
      - platform-tools
      - extra-google-m2repository
    licenses:
      - "android-sdk-preview-license-52d11cd2"
      - "android-sdk-license-.+"
      - "google-gdk-license-.+"

  - &android-cache
    yarn: true
    bundler: true
    directories:
      - ~/.cache/yarn
      - ~/.gradle/caches
      - ~/.gradle/wrapper
      - ~/.android/build-cache
      - ./app/node_modules

  - &ios-cache
    yarn: true
    bundler: true
    directories:
      - ~/.rncache
      - ~/Library/Caches/Yarn
      - ~/Library/Caches/CocoaPods
      - ./app/node_modules

  - &test-cache
    yarn: true
    directories:
      - ~/.cache/yarn
      - ./app/node_modules

jobs:
  include:
    - stage: ios-production
      os: osx
      osx_image: xcode10.1
      language: node_js
      cache: *ios-cache
      node_js:
        - lts/*
      before_install:
        - npm install -g yarn
      install:
        - "./write-ios-keys.sh production"
        - "./install-deps-ios.sh"
      script:
        - cd app
        - yarn content-script:ci
        - yarn ios:prod

env:
  global:
    - APP_NAME="Memex Go"
    - 'DEVELOPER_NAME="iPhone Distribution: WorldBrain UG (haftungsbeschränkt)"'
    - PROFILE_NAME="travis"
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
