jobs:
  include:
    - stage: ios-beta
      # if: branch = develop AND type = push
      os: osx
      osx_image: xcode11.3
      language: node_js
      node_js:
        - lts/*
      before_install:
        - "./write-keys.sh"
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn=1.21.1-1
      install:
        - git submodule update --init --recursive
        - yarn install --frozen-lockfile
        - cd app/ios/
        - pod install
        - cd ..
      install:
        - git submodule update --init --recursive
        - yarn install --frozen-lockfile
      script:
        - yarn ios:beta
env:
  global:
    - APP_NAME="Memex Mobile"
    - 'DEVELOPER_NAME="iPhone Distribution: WorldBrain UG (haftungsbeschränkt)"'
    - PROFILE_NAME="travis"
